# Generated by Django 5.1.6 on 2025-04-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doglink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catlink',
        ),
        migrations.DeleteModel(
            name='Doglink',
        ),
    ]
