# Generated by Django 5.0.7 on 2024-10-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_create',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_public',
            new_name='published_date',
        ),
    ]
