# Generated by Django 5.0.7 on 2024-11-24 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(default=None, max_length=200)),
                ('secondname', models.CharField(default=None, max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('secondpassword', models.CharField(max_length=200)),
                ('email', models.CharField(default=None, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
