# Generated by Django 5.0.7 on 2024-11-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secondpassword',
            new_name='password2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
