# Generated by Django 5.0.7 on 2024-11-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_secondpassword_user_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='data_create',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
