# Generated by Django 5.0.7 on 2024-11-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_created_date_user_data_create_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
