# Generated by Django 4.2.16 on 2025-06-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_try', models.CharField(max_length=100)),
                ('second_try', models.CharField(max_length=100)),
                ('third_try', models.CharField(max_length=100)),
                ('mrad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableIpAddressSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.table')),
            ],
        ),
    ]
