# Generated by Django 4.2.16 on 2025-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='target',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
